import type { Metadata } from "next";
import localFont from "next/font/local";
import { ChakraProvider } from "@chakra-ui/react";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Finance Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <title>Fina App</title>
    </head>
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ChakraProvider >{children}</ChakraProvider>
    </body>
  </html>
  );
}
